import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import '../styles/globals.scss';
import { LoginContextProvider } from "../../common/context/loginContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
				<LoginContextProvider>
					{children}
				</LoginContextProvider>
			</body>
    </html>
  );
}
